server:
    port: 8080

liquibase:
    change-log: classpath:config/liquibase/master.xml
    contexts: openshift

spring:
    profiles:
        active: openshift
    datasource:
        driverClassName: org.postgresql.Driver        
        url: jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/${OPENSHIFT_APP_NAME}
        username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
        password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}
        test-on-borrow: true
        test-on-return: true
        test-while-idle: true
        validation-query: SELECT 1;
        validation-interval: 30000
        remove-abandoned: true
        remove-abandoned-timeout: 60

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    thymeleaf:
        mode: XHTML
        cache: true

http:
    cache:
        timeToLiveInDays: 31

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
        
mail:
    username: ${SENDGRID_USERNAME}
    password: ${SENDGRID_PASSWORD}
    protocol: sendgrid
