server:
    port: 8080

liquibase:
    context: prod

spring:
    profiles:
        active: openshift
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url:
        databaseName: ${OPENSHIFT_APP_NAME}
        portNumber: ${OPENSHIFT_POSTGRESQL_DB_PORT}
        serverName: ${OPENSHIFT_POSTGRESQL_DB_HOST}
        username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
        password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    thymeleaf:
        mode: XHTML
        cache: true

http:
    cache:
        timeToLiveInDays: 31

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
